module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['.'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
          '.test.ts{x}',
        ],
        alias: {
          '@Api': './src/Api',
          '@Api/*': './src/Api/*',
          '@Context': './src/Context',
          '@Context/*': './src/Context/*',
          '@Constants': './src/Constants',
          '@Constants/*': './src/Constants/*',
          '@Screens': './src/Screens',
          '@Screens/*': './src/Screens/*',
          '@Styles': './src/Styles',
          '@Styles/*': './src/Styles/*',
          '@Components': './src/Components',
          '@Components/*': './src/Components/*',
          '@Navigation': './src/Navigation',
          '@Navigation/*': './src/Navigation/*',
          '@Utils': './src/Utils',
          '@Utils/*': './src/Utils/*',
          '@Store': './src/Store',
          '@Store/*': './src/Store/*',
          '@Images': './src/Assets/Images',
          '@Images/*': './src/Assets/Images/*',
          '@Icons': './src/Assets/Icons',
          '@Icons/*': './src/Assets/Icons/*',
          '@Fonts': './src/Assets/Fonts',
          '@Fonts/*': './src/Assets/Fonts/*',
          '@Assets': './src/Assets',
          '@Hooks': './src/Hooks',
          '@Hooks/*': './src/Hooks/*',
          '@Data': './src/Data',
          '@Data/*': './src/Data/*',
          '@Providers': './src/Providers',
          '@Providers/*': './src/Providers/*',
          '@Core': './src/Core',
          '@Core/*': './src/Core/*',
          '@Features': './src/Features',
          '@Features/*': './src/Features/*',
          '@Services': './src/Services',
          '@Services/*': './src/Services/*',
        },
      },
    ],
    'react-native-reanimated/plugin',
  ],
  env: {
    production: {
      plugins: ['transform-remove-console'],
    },
  },
};
