name: 'Code'
on:
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint:ci
